services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: musicsystem
      POSTGRES_PASSWORD: olek
      POSTGRES_USER: olek
    ports:
      - '5432'
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'