services:
  postgres:
    container_name: postgres-music-system
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  musicsystem-api:
    container_name: musicsystem-api
    image: olek2303/musicsystem:1.0.1
    ports:
      - 8088:8088
    depends_on:
      - postgres
    networks:
      - spring-demo
    restart: unless-stopped
  musicsystem-front:
    container_name: musicsystem-front
    image: olek2303/musicsystem-front:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - musicsystem-api
    restart: unless-stopped
volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge