services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: musicsystem
      POSTGRES_PASSWORD: olek
      POSTGRES_USER: olek
    ports:
      - '5432'
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025