spring:
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    name: musicsystem
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: olek
    password: olek
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

springdoc:
  default-produces-media-type: application/json